### ISSUE TITLE
Using HOST_TUN_PROTOCOL=tcp doesn't have any effect at all.

### ISSUE THREAD

**Issue by AhmedAhmedEG** [alekslitvinenk/docker-openvpn#265]
**Describe the bug**
Setting HOST_TUN_PROTOCOL=tcp should configure the server to use tcp but this is not the case, it just never works, is this even normal?

Here's the command I am using:-

> docker run -it --cap-add=NET_ADMIN -p 1194:1194/tcp -p 80:8080/tcp -e HOST_ADDR=127.0.0.1 -e HOST_TUN_PROTOCOL=tcp --name dockovpn alekslitvinenk/openvpn

**Comment by ypurpl** [comment]
having this too. I used the docker compose variant:
```yml
environment:
      HOST_ADDR: ${HOST_ADDR}
      HOST_TUN_PROTOCOL: tcp
```
